### ISSUE TITLE
[bug-website module]  website URL changed to https://www.mgeko.cc/

### ISSUE THREAD

**Issue by xx255q** [dazedcat19/FMD#1476]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 latest

### Describe the bug

https://www.mgeko.cc/ is new URL

Example of a series:

https://www.mgeko.cc/manga/hidden-house-in-the-apocalypse/
https://www.mgeko.cc/manga/tales-of-a-shinning-sword/

**Comment by xx255q** [comment]
Very Ssad, i tried to use AI to code it myself but just changiong the URL from .com to.cc failed. Then it said it needed flavesolveer so still stuck. please send help!

**Comment by Qizmo** [comment]
Oh! Just noticed that I'm not getting anything from Mgeko too. Hope this is fixed soon.

Edit: Mgeko.com is loading normally now. Haven't change to mgeko.cc though.

**Comment by xx255q** [comment]
You mean you can download again?

EDIT: I just tried and its still failing
